[package]
name = "testurls"
version = "0.1.0"
authors = ["Mark Pritchard <mpritcha@gmail.com>"]
edition = "2018"

[dependencies]
feed-rs = { path = "../feed-rs", features = ["parse-html"] }
reqwest = { version = "0.11", features = ["blocking"] }
